apply plugin: 'java-library'
apply plugin: 'kotlin'

dependencies {
    final KOTLIN_VERSION = '1.9.23'
    final KOIN_VERSION = '2.0.1'

    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$KOTLIN_VERSION"
    implementation "org.jetbrains.kotlin:kotlin-reflect:$KOTLIN_VERSION"

    api "io.insert-koin:koin-core:$KOIN_VERSION"

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.mockito:mockito-core:5.22.0'
    testImplementation 'org.mockito.kotlin:mockito-kotlin:5.4.0'
    testImplementation "io.insert-koin:koin-test:$KOIN_VERSION"
}

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        final KOTLIN_VERSION = '1.9.23'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$KOTLIN_VERSION"
    }
}
repositories {
    mavenCentral()
}
compileKotlin {
    kotlinOptions {
        jvmTarget = "21"
    }
}
compileTestKotlin {
    kotlinOptions {
        jvmTarget = "21"
    }
}
